# Generated by Django 3.1.4 on 2020-12-19 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='answer',
            new_name='quiz_name',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('question_name', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('option_id', models.AutoField(default=None, primary_key=True, serialize=False, unique=True)),
                ('option_name', models.CharField(max_length=200)),
                ('is_answer', models.BooleanField(default=False)),
                ('question', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Quiz.quiz')),
            ],
        ),
    ]
