# Generated by Django 3.1.4 on 2020-12-19 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20201219_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
